# Use an appropriate base image
FROM alpine:latest

RUN apk update && apk add --no-cache rsyslog rsyslog-relp \
    && rm -rf /var/cache/apk/*

EXPOSE 2514

# Copy the rsyslog configuration file from the context
COPY rsyslog.conf /etc/rsyslog.conf

# Command to run rsyslog in the foreground
CMD ["rsyslogd", "-n", "-f", "/etc/rsyslog.conf"]