# Start with a minimal base image
FROM ubuntu:latest

# Install rsyslog and necessary dependencies
RUN apt-get update && \
    apt-get install -y rsyslog && \
    apt-get install -y rsyslog-relp && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose ports for rsyslog
EXPOSE 514/udp 514/tcp

# Set the command to start rsyslog
CMD ["rsyslogd", "-n"]