
# Create Storage for Rsyslog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-static-pvc
  namespace: gic-asenhoradosaneis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
