# Create MongoDB deployment
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: gic-asenhoradosaneis
spec:
  serviceName: "mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.deti/gic-asenhoradosaneis/mongodb
        command:
        - mongod
        - "--config"
        - "/config/mongod.conf"
        volumeMounts:
        - name: mongodb-config
          mountPath: /config
        - name: mongodb-data
          mountPath: /data/db
        ports:
        - name: mongodb
          containerPort: 27017
      restartPolicy: Always
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi

# Create Job for Mongo Master
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongodb
  namespace: gic-asenhoradosaneis
spec:
  template:
    spec:
      containers:
      - name: init-mongodb
        image: registry.deti/gic-asenhoradosaneis/mongodb
        command:
        - "sh"
        - "-c"
        - >
          until mongosh --host mongodb-0.mongodb.gic-asenhoradosaneis.svc.cluster.local --eval "print(\"Connection Successfull to MongoDB 0\")"; do
            sleep 1;
          done &&
          until mongosh --host mongodb-1.mongodb.gic-asenhoradosaneis.svc.cluster.local --eval "print(\"Connection Successfull to MongoDB 1\")"; do
            sleep 1;
          done &&
          until mongosh --host mongodb-2.mongodb.gic-asenhoradosaneis.svc.cluster.local --eval "print(\"Connection Successfull to MongoDB 2\")"; do
            sleep 1;
          done &&
          mongosh --host mongodb-0.mongodb.gic-asenhoradosaneis.svc.cluster.local --eval "
            rs.initiate({ 
              _id: 'rs0', 
              members: [
                { _id: 0, host: 'mongodb-0.mongodb.gic-asenhoradosaneis.svc.cluster.local:27017' }, 
                { _id: 1, host: 'mongodb-1.mongodb.gic-asenhoradosaneis.svc.cluster.local:27017' }, 
                { _id: 2, host: 'mongodb-2.mongodb.gic-asenhoradosaneis.svc.cluster.local:27017' }
              ] 
            })
          "
      restartPolicy: OnFailure

# Create Service for MongoDB
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: gic-asenhoradosaneis
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

# Config Map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: gic-asenhoradosaneis
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: rs0