---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: gic-asenhoradosaneis
spec:
  serviceName: "redis-replica"
  replicas: 2
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
      - name: redis-replica
        image: registry.deti/gic-asenhoradosaneis/redis
        ports:
        - containerPort: 6379
        - containerPort: 26379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        env:
        - name: REDIS_REPLICATION_MODE
          value: "replica"
        - name: REDIS_MASTER_HOST
          value: "redis-primary.gic-asenhoradosaneis"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-primary
  namespace: gic-asenhoradosaneis
spec:
  serviceName: "redis-primary"
  replicas: 1
  selector:
    matchLabels:
      app: redis-primary
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      containers:
      - name: redis-primary
        image: registry.deti/gic-asenhoradosaneis/redis
        ports:
        - containerPort: 6379
        - containerPort: 26379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        env:
        - name: REDIS_REPLICATION_MODE
          value: "master"
        - name: REDIS_MASTER_HOST
          value: "redis-primary.gic-asenhoradosaneis"
        volumeMounts:
        - name: config-volume
          mountPath: /redis-master
      volumes:
      - name: config-volume
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: gic-asenhoradosaneis
spec:
  ports:
  - port: 6379
    name: redis-replica
  selector:
    app: redis-replica

---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: gic-asenhoradosaneis
spec:
  ports:
  - port: 6379
    name: redis-primary
  selector:
    app: redis-primary

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: gic-asenhoradosaneis
data:
  redis.conf: |
    # Redis configuration
    logfile /var/log/redis-server.log
    syslog-enabled yes
    syslog-ident redis-primary
    syslog-facility local0
    bind 0.0.0.0
    port 6379