---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  namespace: gic-asenhoradosaneis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: registry.deti/gic-asenhoradosaneis/rsyslog
        ports:
          - containerPort: 514
            protocol: UDP
          - containerPort: 514
            protocol: TCP
        volumeMounts:
            - name: config-volume
              mountPath: /etc/rsyslog.conf
              subPath: rsyslog.conf
      volumes:
        - name: config-volume
          configMap:
            name: rsyslog-config

---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: gic-asenhoradosaneis
spec:
  selector:
    app: rsyslog
  ports:
  - name: udp
    protocol: UDP
    port: 514
    targetPort: 514
  - name: tcp
    protocol: TCP
    port: 514
    targetPort: 514

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-config
  namespace: gic-asenhoradosaneis
data:
  rsyslog.conf: |
    module(load="imudp")
    input(type="imudp" port="514")
    module(load="imtcp")
    input(type="imtcp" port="514")

    local0.* /var/log/gic-asenhoradosaneis-mongodb.log
    local1.* /var/log/gic-asenhoradosaneis-redis.log
    local2.* /var/log/gic-asenhoradosaneis-webclients.log
    local3.* /var/log/gic-asenhoradosaneis-shopping-server.log
    local4.* /var/log/gic-asenhoradosaneis-management-server.log

    *.* /var/log/gic-asenhoradosaneis-syslog.log
    stop