---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  namespace: gic-asenhoradosaneis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: registry.deti/gic-asenhoradosaneis/rsyslog:v1
        ports:
        - containerPort: 514

---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: gic-asenhoradosaneis
spec:
  selector:
    app: rsyslog
  ports:
  - protocol: TCP
    port: 514
    targetPort: 514

# # Configure Traefik for Shopping
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: rsyslog-gic-asenhoradosaneis-k3s
#   namespace: gic-asenhoradosaneis
#   annotations:
#     spec.ingressClassName: traefik
#     traefik.ingress.kubernetes.io/router.entrypoints: web
#     # traefik.ingress.kubernetes.io/redirect-entry-point: https
#     traefik.ingress.kubernetes.io/redirect-permanent: "true"
#     traefik.ingress.kubernetes.io/preserve-host: "true"
# spec:
#   rules:
#   - host: rsyslog.gic-asenhoradosaneis.k3s
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: rsyslog
#             port: 
#               number: 514