# Create Rsyslog deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-deployment
  namespace: gic-asenhoradosaneis
  labels:
    app: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: registry.deti/gic-asenhoradosaneis/rsyslog:v1
        ports:
        - containerPort: 5140
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
        imagePullPolicy: Always
        volumeMounts:
          - name: rsyslog-static
            mountPath: "/var/log"
        volumeMounts:
        - name: rsyslog-config
          mountPath: /etc/rsyslog.d
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rsyslog-static
          persistentVolumeClaim:
            claimName: rsyslog-static-pvc
        - name: rsyslog-config
          configMap:
            name: rsyslog-d

# Create Service for Rsyslog
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-server
  namespace: gic-asenhoradosaneis
spec:
  selector:
    app: rsyslog-server
  ports:
    - port: 5000
      targetPort: 5140

# Create ConfigMap for Rsyslog
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-d
  namespace: gic-asenhoradosaneis
  labels:
    app: rsyslog
data:
  filelog.conf: |
    # http://www.rsyslog.com/doc/

    # Output
    $template DynaFile,"/var/log/container-%HOSTNAME%.log"

    # Actions
    *.* -?DynaFile              # one file for every device
  imtcp.conf: |
    module(load="imtcp")
    input(type="imtcp" port="514")
  imudp.conf: |
    module(load="imudp")
    input(type="imudp" port="514")

# Create Horizontal Pod Autoscaler for Wordpress
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rsyslog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rsyslog
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75