# Create Wordpress deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: gic-asenhoradosaneis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: registry.deti/gic-asenhoradosaneis/wordpress
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

# Create Service for Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: gic-asenhoradosaneis
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wordpress