From ubuntu
RUN apt update && apt install apache2 -y

# Copy your website files into the container
COPY /var/www/html .

# # Set permissions for WordPress files
#RUN chown -R www-data:www-data /var/www/html

RUN chmod 777 -R /var/www/html


# Expose port 80 to make the WordPress site accessible
EXPOSE 80
