FROM ubuntu

RUN apt update 
RUN apt install lsb-release curl gpg -y
RUN curl -fsSL https://packages.redis.io/gpg |  gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list

RUN apt-get install redis -y

# ENTRYPOINT ["docker-entrypoint.sh"]


EXPOSE 8379

CMD ["redis-server"]
